export const db = {
  hospitals: [
    {
      id: "hosp_max",
      name: "Max Healthcare",
      tagline: "Where Excellence Meets Compassion",
      description:
        "Max Healthcare is one of India's largest and most comprehensive healthcare networks, providing advanced treatments with world-class facilities and a patient-first approach.",
      logo: "/media/max-logo.png",
      branches: ["branch_max_saket", "branch_max_shalimar_bagh", "branch_max_gurgaon", "branch_max_noida", "branch_max_patparganj"],
      departments: ["Cardiology", "Orthopedics", "Neurosciences", "Oncology", "Gastroenterology", "Urology", "Organ Transplant"],
      facilities: ["24x7 Emergency", "Pharmacy", "ICU", "Diagnostics", "Blood Bank", "Ambulance", "Robotic Surgery"],
      services: ["International Patient Desk", "Teleconsultation", "Home Sample Collection", "Health Check-ups"],
      insurancePartners: ["Star Health", "Max Bupa", "ICICI Lombard", "HDFC ERGO"],
      rating: 4.6,
      reviewCount: 4500,
      website: "https://www.maxhealthcare.in",
      contactEmail: "info@maxhealthcare.in",
      socialLinks: {
        facebook: "https://facebook.com/maxhealthcare",
        instagram: "https://instagram.com/maxhealthcare",
        linkedin: "https://linkedin.com/company/maxhealthcare",
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "hosp_apollo",
      name: "Apollo Hospitals",
      tagline: "Trusted Care. World-Class Expertise.",
      description:
        "Apollo Hospitals is Asia’s foremost integrated healthcare provider, pioneering advanced medical solutions and bringing high-quality healthcare closer to people.",
      logo: "/media/apollo-logo.png",
      branches: ["branch_apollo_delhi", "branch_apollo_chennai", "branch_apollo_bangalore", "branch_apollo_hyderabad", "branch_apollo_kolkata"],
      departments: ["Cardiology", "Oncology", "Nephrology", "Dermatology", "Gastroenterology", "Orthopaedics"],
      facilities: ["24x7 Emergency", "Pharmacy", "Radiology", "Advanced ICU", "Transplant Unit", "Robotic Surgery"],
      services: ["Medical Visa Assistance", "Virtual Consultation", "Health Check-ups"],
      insurancePartners: ["HDFC ERGO", "Care Health", "Bajaj Allianz", "Tata AIG"],
      rating: 4.8,
      reviewCount: 6200,
      website: "https://www.apollohospitals.com",
      contactEmail: "care@apollohospitals.com",
      socialLinks: {
        facebook: "https://facebook.com/apollohospitals",
        instagram: "https://instagram.com/apollohospitals",
        linkedin: "https://linkedin.com/company/apollo-hospitals",
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "hosp_fortis",
      name: "Fortis Healthcare",
      tagline: "Caring for your life, your way.",
      description:
        "Fortis is a leading integrated healthcare provider with a wide network of hospitals across India, offering tertiary and quaternary care with a commitment to clinical excellence.",
      logo: "/media/fortis-logo.png",
      branches: ["branch_fortis_fmri", "branch_fortis_vasant_kunj", "branch_fortis_mumbai", "branch_fortis_bangalore", "branch_fortis_noida"],
      departments: ["Cardiac Sciences", "Orthopaedics", "Oncology", "Neurosciences", "Organ Transplant", "Minimal Access Surgery"],
      facilities: ["Critical Care", "Advanced Diagnostics", "Robotic Surgery", "Blood Bank", "Rehabilitation Services"],
      services: ["Emergency services", "Health check-ups", "Second Opinion"],
      insurancePartners: ["Apollo Munich", "Religare Health", "ICICI Lombard", "Bajaj Allianz"],
      rating: 4.5,
      reviewCount: 5100,
      website: "https://www.fortishealthcare.com",
      contactEmail: "info@fortishealthcare.com",
      socialLinks: {
        facebook: "https://facebook.com/fortishealthcare",
        twitter: "https://twitter.com/fortis_hospital",
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "hosp_medanta",
      name: "Medanta - The Medicity",
      tagline: "Where Healthcare is a Mission",
      description:
        "Founded by renowned cardiac surgeon Dr. Naresh Trehan, Medanta is a multi-super specialty hospital with a focus on cutting-edge technology, research, and patient-centric care.",
      logo: "/media/medanta-logo.png",
      branches: ["branch_medanta_gurgaon", "branch_medanta_lucknow", "branch_medanta_indore", "branch_medanta_patna", "branch_medanta_ranchi"],
      departments: ["Cardiac Sciences", "Oncology", "Neurosciences", "Orthopaedics", "Gastroenterology", "Urology"],
      facilities: ["Robotic Surgery", "Organ Transplant Unit", "24x7 Emergency", "ICU", "Advanced Diagnostics"],
      services: ["International Patient Services", "Teleconsultation", "Home Healthcare"],
      insurancePartners: ["Max Bupa", "HDFC ERGO", "Star Health", "Kotak Mahindra"],
      rating: 4.6,
      reviewCount: 4800,
      website: "https://www.medanta.org",
      contactEmail: "info@medanta.org",
      socialLinks: {
        facebook: "https://facebook.com/medanta",
        linkedin: "https://linkedin.com/company/medanta",
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "hosp_manipal",
      name: "Manipal Hospitals",
      tagline: "Your Health, Our Priority",
      description:
        "Manipal Hospitals is a leading healthcare group in India, recognized for its clinical excellence, patient-centric services, and innovative medical practices.",
      logo: "/media/manipal-logo.png",
      branches: ["branch_manipal_bangalore", "branch_manipal_delhi", "branch_manipal_pune", "branch_manipal_goa", "branch_manipal_jaipur"],
      departments: ["Cardiology", "Nephrology", "Oncology", "Orthopaedics", "Neurology", "Endocrinology"],
      facilities: ["Organ Transplant", "Advanced Diagnostics", "24x7 Emergency", "Critical Care", "Rehabilitation"],
      services: ["Teleconsultation", "Home Healthcare", "Medical Tourism"],
      insurancePartners: ["Bajaj Allianz", "Star Health", "Max Bupa", "Future Generali"],
      rating: 4.5,
      reviewCount: 3900,
      website: "https://www.manipalhospitals.com",
      contactEmail: "info@manipalhospitals.com",
      socialLinks: {
        facebook: "https://facebook.com/manipalhospitals",
        linkedin: "https://linkedin.com/company/manipal-hospitals",
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  branches: [
    {
      id: "branch_max_saket",
      hospitalId: "hosp_max",
      name: "Max Super Speciality Hospital - Saket",
      address: "1, 2, Press Enclave Rd, Saket, New Delhi, Delhi 110017",
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      phone: "+91-11-26515050",
      email: "saket@maxhealthcare.in",
      geo: { lat: 28.5246, lon: 77.201 },
      operatingHours: { weekdays: "08:00 AM - 08:00 PM", weekends: "09:00 AM - 06:00 PM", emergency: "24x7" },
      departments: ["Cardiology", "Orthopedics", "Neurosciences", "Oncology"],
      treatments: ["treat_angioplasty", "treat_knee_replacement", "treat_spine_surgery", "treat_cancer_therapy"],
      doctors: ["dr_balbir_singh", "dr_sanjay_sachdeva", "dr_amit_sharma", "dr_rekha_rao", "dr_harit_chaturvedi"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/max-saket" },
      images: ["/media/max-saket-1.jpg", "/media/max-saket-2.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.maxhealthcare.in/book-appointment/saket",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_max_shalimar_bagh",
      hospitalId: "hosp_max",
      name: "Max Super Speciality Hospital - Shalimar Bagh",
      address: "FC-50, C & D Block, Shalimar Bagh, New Delhi, Delhi 110088",
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      phone: "+91-11-45545555",
      email: "shalimarb@maxhealthcare.in",
      geo: { lat: 28.718, lon: 77.165 },
      operatingHours: { weekdays: "08:00 AM - 07:00 PM", weekends: "09:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Oncology", "Gastroenterology", "Nephrology", "Urology"],
      treatments: ["treat_kidney_transplant", "treat_colonoscopy", "treat_chemotherapy", "treat_robotic_surgery_prostate"],
      doctors: ["dr_sanjeev_gogna", "dr_subhash_gupta", "dr_manish_gupta", "dr_harsh_jain", "dr_r_k_chopra"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/max-shalimar-bagh" },
      images: ["/media/max-shalimar-bagh-1.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.maxhealthcare.in/book-appointment/shalimar-bagh",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_apollo_delhi",
      hospitalId: "hosp_apollo",
      name: "Indraprastha Apollo Hospitals",
      address: "Sarita Vihar, Delhi Mathura Road, New Delhi, Delhi 110076",
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      phone: "+91-11-26925858",
      email: "info@apollohospitals.com",
      geo: { lat: 28.528, lon: 77.288 },
      operatingHours: { weekdays: "07:30 AM - 07:30 PM", weekends: "08:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Cardiology", "Oncology", "Neurosciences", "Gastroenterology", "Orthopaedics"],
      treatments: ["treat_cabg", "treat_liver_transplant", "treat_brain_tumor_surgery"],
      doctors: ["dr_subhash_mishra", "dr_anupam_singh", "dr_prashant_jain", "dr_nupur_sharma", "dr_manish_aggarwal"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/apollo-delhi" },
      images: ["/media/apollo-delhi-1.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.apollohospitals.com/book-appointment/delhi",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_apollo_chennai",
      hospitalId: "hosp_apollo",
      name: "Apollo Main Hospital, Greams Road",
      address: "21, Greams Lane, Off Greams Road, Chennai, Tamil Nadu 600006",
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
      phone: "+91-44-28293333",
      email: "apollo_chennai@apollohospitals.com",
      geo: { lat: 13.0641, lon: 80.2599 },
      operatingHours: { weekdays: "07:30 AM - 07:30 PM", weekends: "08:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Cardiology", "Oncology", "Gastroenterology", "Nephrology"],
      treatments: ["treat_cardiac_stenting", "treat_kidney_transplant", "treat_liver_transplant"],
      doctors: ["dr_anita_ramesh", "dr_r_krishnamurthy", "dr_s_krishnamoorthy", "dr_sudha_rao", "dr_vasantha_devi"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/apollo-chennai" },
      images: ["/media/apollo-chennai-1.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.apollohospitals.com/book-appointment/chennai",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_fortis_fmri",
      hospitalId: "hosp_fortis",
      name: "Fortis Memorial Research Institute (FMRI)",
      address: "Sector 44, Opposite HUDA City Centre, Gurgaon, Haryana 122002",
      city: "Gurgaon",
      state: "Haryana",
      country: "India",
      phone: "+91-124-4962200",
      email: "fmri@fortishealthcare.com",
      geo: { lat: 28.4682, lon: 77.0706 },
      operatingHours: { weekdays: "08:00 AM - 08:00 PM", weekends: "09:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Cardiac Sciences", "Oncology", "Orthopaedics", "Neurosciences", "Liver Transplant"],
      treatments: ["treat_heart_bypass", "treat_liver_transplant_fmri", "treat_joint_replacement"],
      doctors: ["dr_subhash_agarwal", "dr_rahul_bhargava", "dr_s_k_aggarwal", "dr_gagan_mathur", "dr_anurag_garg"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/fortis-fmri" },
      images: ["/media/fortis-fmri-1.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.fortishealthcare.com/book-appointment/fmri",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_fortis_mumbai",
      hospitalId: "hosp_fortis",
      name: "Fortis Hospital, Mulund",
      address: "Mulund - Goregaon Link Road, Mulund West, Mumbai, Maharashtra 400078",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      phone: "+91-22-25688000",
      email: "mulund@fortishealthcare.com",
      geo: { lat: 19.141, lon: 72.934 },
      operatingHours: { weekdays: "08:00 AM - 08:00 PM", weekends: "09:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Cardiology", "Oncology", "Orthopaedics", "Organ Transplant"],
      treatments: ["treat_heart_bypass", "treat_kidney_transplant", "treat_joint_replacement"],
      doctors: ["dr_anvay_mulay", "dr_ramakanta_panda", "dr_b_k_mishra", "dr_suresh_rao", "dr_vivek_mishra"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/fortis-mumbai" },
      images: ["/media/fortis-mumbai-1.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.fortishealthcare.com/book-appointment/mulund",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_medanta_gurgaon",
      hospitalId: "hosp_medanta",
      name: "Medanta - The Medicity, Gurugram",
      address: "Sector 38, Gurugram, Haryana, 122001",
      city: "Gurgaon",
      state: "Haryana",
      country: "India",
      phone: "+91-124-4141414",
      email: "info.gurgaon@medanta.org",
      geo: { lat: 28.4239, lon: 77.054 },
      operatingHours: { weekdays: "08:00 AM - 08:00 PM", weekends: "09:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Cardiac Sciences", "Neurosciences", "Orthopaedics", "Oncology"],
      treatments: ["treat_heart_bypass_medanta", "treat_spine_surgery", "treat_robotic_joint_replacement"],
      doctors: ["dr_naresh_trehan", "dr_v_p_singh", "dr_ashok_seth", "dr_rajiv_jain", "dr_kushal_gupta"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/medanta-gurgaon" },
      images: ["/media/medanta-gurgaon-1.jpg", "/media/medanta-gurgaon-2.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.medanta.org/book-appointment/gurgaon",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "branch_manipal_bangalore",
      hospitalId: "hosp_manipal",
      name: "Manipal Hospital, Old Airport Road",
      address: "98, HAL Old Airport Rd, Kodihalli, Bengaluru, Karnataka 560017",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      phone: "+91-80-40344034",
      email: "info.bangalore@manipalhospitals.com",
      geo: { lat: 12.9667, lon: 77.6433 },
      operatingHours: { weekdays: "08:00 AM - 07:00 PM", weekends: "09:00 AM - 05:00 PM", emergency: "24x7" },
      departments: ["Cardiology", "Nephrology", "Oncology", "Orthopaedics"],
      treatments: ["treat_kidney_transplant", "treat_cardiac_stenting", "treat_oncology_treatment"],
      doctors: ["dr_sathish_chandra", "dr_sanjay_rao", "dr_b_t_krishna", "dr_ashok_kumar", "dr_s_r_gupta"],
      mapLinks: { googleMaps: "http://googleusercontent.com/maps.google.com/manipal-bangalore" },
      images: ["/media/manipal-bangalore-1.jpg"],
      parkingAvailable: true,
      wheelchairAccessible: true,
      appointmentBookingLink: "https://www.manipalhospitals.com/bangalore/book-appointment",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  doctors: [
    {
      id: "dr_balbir_singh",
      name: "Dr. Balbir Singh",
      title: "Chairman, Cardiac Sciences",
      specialties: ["Interventional Cardiology", "Electrophysiology"],
      experienceYears: 25,
      languages: ["English", "Hindi"],
      affiliations: ["branch_max_saket"],
      contact: { phone: "+91-98xxxxxx", email: "drbalbir.singh@maxhealthcare.in" },
      about: "Pioneer in interventional cardiology and has performed over 20,000 procedures. Recipient of the Padma Shri award.",
      education: ["MBBS - AIIMS Delhi", "DM - Cardiology"],
      memberships: ["Cardiological Society of India"],
      awards: ["Padma Shri"],
      publications: [],
      socialLinks: { linkedin: "https://linkedin.com/in/drbalbirsingh" },
      attachments: ["/media/dr-balbir-singh.jpg"],
      rating: 4.8,
      reviewCount: 750,
    },
    {
      id: "dr_sanjay_sachdeva",
      name: "Dr. Sanjay Sachdeva",
      title: "Senior Consultant, ENT",
      specialties: ["ENT", "Cochlear Implants"],
      experienceYears: 20,
      languages: ["English", "Hindi"],
      affiliations: ["branch_max_saket"],
      contact: { phone: "+91-99xxxxxx", email: "drsanjay.sachdeva@maxhealthcare.in" },
      about: "Expert in cochlear implants and endoscopic sinus surgeries.",
      education: ["MBBS, MS - ENT"],
      memberships: ["Association of Otolaryngologists of India"],
      awards: [],
      publications: [],
      socialLinks: {},
      attachments: [],
      rating: 4.7,
      reviewCount: 350,
    },
    {
      id: "dr_harit_chaturvedi",
      name: "Dr. Harit Chaturvedi",
      title: "Chairman, Max Institute of Cancer Care",
      specialties: ["Surgical Oncology", "Oncology"],
      experienceYears: 28,
      languages: ["English", "Hindi"],
      affiliations: ["branch_max_saket", "branch_max_shalimar_bagh"],
      contact: { phone: "+91-98xxxxxx", email: "drharit.chaturvedi@maxhealthcare.in" },
      about: "One of the most respected surgical oncologists in India, with expertise in robotic and minimally invasive cancer surgeries.",
      education: ["MBBS, MS - General Surgery", "MCh - Surgical Oncology"],
      memberships: ["Indian Association of Surgical Oncology"],
      awards: ["Best Surgical Oncologist Award"],
      publications: [],
      socialLinks: {},
      attachments: [],
      rating: 4.9,
      reviewCount: 650,
    },
    {
      id: "dr_prashant_jain",
      name: "Dr. Prashant Jain",
      title: "Senior Consultant, Gastroenterology",
      specialties: ["Gastroenterology", "Hepatology"],
      experienceYears: 18,
      languages: ["English", "Hindi"],
      affiliations: ["branch_apollo_delhi"],
      contact: { phone: "+91-97xxxxxx", email: "drprashant.jain@apollohospitals.com" },
      about: "Specializes in managing complex gastrointestinal and liver diseases. Known for diagnostic and therapeutic endoscopy.",
      education: ["MBBS, MD, DM - Gastroenterology"],
      memberships: ["Indian Society of Gastroenterology"],
      awards: [],
      publications: [],
      socialLinks: {},
      attachments: [],
      rating: 4.6,
      reviewCount: 210,
    },
    {
      id: "dr_rahul_bhargava",
      name: "Dr. Rahul Bhargava",
      title: "Director, Hematology & Bone Marrow Transplant",
      specialties: ["Hematology", "Bone Marrow Transplant"],
      experienceYears: 20,
      languages: ["English", "Hindi"],
      affiliations: ["branch_fortis_fmri"],
      contact: { phone: "+91-99xxxxxx", email: "drrahul.bhargava@fortishealthcare.com" },
      about: "Pioneer in bone marrow transplants in India, credited with over 1000 successful transplants.",
      education: ["MBBS, MD - Medicine"],
      memberships: ["Indian Society of Hematology"],
      awards: ["Best Hematologist Award"],
      publications: [],
      socialLinks: {},
      attachments: ["/media/dr-rahul-bhargava.jpg"],
      rating: 4.8,
      reviewCount: 520,
    },
    {
      id: "dr_anvay_mulay",
      name: "Dr. Anvay Mulay",
      title: "Head, Cardiac Surgery",
      specialties: ["Cardiothoracic Surgery", "Heart Transplant"],
      experienceYears: 24,
      languages: ["English", "Marathi", "Hindi"],
      affiliations: ["branch_fortis_mumbai"],
      contact: { phone: "+91-97xxxxxx", email: "dranvay.mulay@fortishealthcare.com" },
      about: "Led the team that performed the first heart transplant in Mumbai. Specializes in complex cardiac and vascular surgeries.",
      education: ["MBBS, MS, MCh - Cardiothoracic and Vascular Surgery"],
      memberships: ["Indian Association of Cardiovascular and Thoracic Surgeons"],
      awards: ["First Heart Transplant in Mumbai Award"],
      publications: [],
      socialLinks: {},
      attachments: ["/media/dr-anvay-mulay.jpg"],
      rating: 4.9,
      reviewCount: 480,
    },
    {
      id: "dr_ashok_seth",
      name: "Dr. Ashok Seth",
      title: "Chairman, Fortis Escorts Heart Institute",
      specialties: ["Interventional Cardiology"],
      experienceYears: 35,
      languages: ["English", "Hindi"],
      affiliations: ["branch_fortis_fmri"],
      contact: { phone: "+91-98xxxxxx", email: "drashok.seth@fortishealthcare.com" },
      about: "Holds the Guinness World Record for the most number of procedures done, including angioplasties and stents.",
      education: ["MBBS, MD, DM - Cardiology"],
      memberships: ["Cardiological Society of India"],
      awards: ["Guinness World Record Holder", "Padma Bhushan"],
      publications: [],
      socialLinks: {},
      attachments: ["/media/dr-ashok-seth.jpg"],
      rating: 4.9,
      reviewCount: 990,
    },
    {
      id: "dr_v_p_singh",
      name: "Dr. V.P. Singh",
      title: "Chairman, Institute of Neurosciences",
      specialties: ["Neurosurgery", "Spine Surgery"],
      experienceYears: 30,
      languages: ["English", "Hindi"],
      affiliations: ["branch_medanta_gurgaon"],
      contact: { phone: "+91-99xxxxxx", email: "dr.vpsingh@medanta.org" },
      about: "An internationally recognized neurosurgeon specializing in complex cranial and spinal surgeries.",
      education: ["MBBS, MS, MCh - Neurosurgery"],
      memberships: ["Neurological Society of India"],
      awards: [],
      publications: [],
      socialLinks: {},
      attachments: ["/media/dr-v-p-singh.jpg"],
      rating: 4.7,
      reviewCount: 600,
    },
    {
      id: "dr_sathish_chandra",
      name: "Dr. Sathish Chandra",
      title: "Chief of Cardiology",
      specialties: ["Interventional Cardiology"],
      experienceYears: 22,
      languages: ["English", "Kannada", "Hindi"],
      affiliations: ["branch_manipal_bangalore"],
      contact: { phone: "+91-98xxxxxx", email: "drsathish.chandra@manipalhospitals.com" },
      about: "Expert in complex coronary interventions, device implantations, and cardiac imaging.",
      education: ["MBBS, MD, DM (Cardiology)"],
      memberships: ["Cardiological Society of India"],
      awards: [],
      publications: [],
      socialLinks: {},
      attachments: [],
      rating: 4.6,
      reviewCount: 420,
    },
    {
      id: "dr_ramakanta_panda",
      name: "Dr. Ramakanta Panda",
      title: "Chief Consultant, Cardiovascular Thoracic Surgery",
      specialties: ["Cardiac Surgery", "Minimally Invasive Surgery"],
      experienceYears: 35,
      languages: ["English", "Hindi"],
      affiliations: ["branch_fortis_mumbai"],
      contact: { phone: "+91-98xxxxxx", email: "drramakanta.panda@fortishealthcare.com" },
      about: "Known for performing 'Redo Coronary Artery Bypass Grafting' surgery and is among the top heart surgeons globally.",
      education: ["MBBS, MCh - Cardio Thoracic and Vascular Surgery"],
      memberships: ["Indian Association of Cardiovascular and Thoracic Surgeons"],
      awards: ["Padma Bhushan"],
      publications: [],
      socialLinks: {},
      attachments: ["/media/dr-ramakanta-panda.jpg"],
      rating: 4.9,
      reviewCount: 950,
    },
  ],
  treatments: [
    {
      id: "treat_angioplasty",
      name: "Angioplasty (PCI)",
      slug: "angioplasty-pci",
      department: "Cardiology",
      description: "A minimally invasive procedure to restore blood flow in blocked arteries using a balloon and a stent.",
      duration_minutes: 90,
      tags: ["cardiology", "angioplasty", "heart"],
      starting_price: 50000,
      price_range: { min: 50000, max: 150000 },
      branches_available: ["branch_max_saket", "branch_apollo_delhi"],
      related_doctors: ["dr_balbir_singh", "dr_ashok_seth"],
      faqs: [
        { q: "How long is the hospital stay?", a: "Typically 1-2 days of hospitalization." },
        { q: "Is it painful?", a: "Mild discomfort may occur but sedation is given." },
      ],
      attachments: ["/media/angioplasty-brochure.pdf"],
    },
    {
      id: "treat_knee_replacement",
      name: "Total Knee Replacement",
      slug: "total-knee-replacement",
      department: "Orthopedics",
      description: "Surgical replacement of a damaged knee joint with prosthetics to relieve pain and restore function.",
      duration_minutes: 120,
      tags: ["orthopedics", "joint", "surgery"],
      starting_price: 120000,
      price_range: { min: 120000, max: 250000 },
      branches_available: ["branch_max_saket", "branch_fortis_fmri", "branch_fortis_mumbai"],
      related_doctors: ["dr_s_k_aggarwal"],
      faqs: [],
      attachments: [],
    },
    {
      id: "treat_spine_surgery",
      name: "Spine Surgery",
      slug: "spine-surgery",
      department: "Neurosciences",
      description: "Surgical procedures to treat conditions of the spine, including disc herniation, spinal stenosis, and spinal tumors.",
      duration_minutes: 180,
      tags: ["neurosurgery", "spine", "surgery"],
      starting_price: 100000,
      price_range: { min: 100000, max: 500000 },
      branches_available: ["branch_max_saket", "branch_medanta_gurgaon", "branch_fortis_fmri"],
      related_doctors: ["dr_v_p_singh"],
      faqs: [],
      attachments: [],
    },
    {
      id: "treat_liver_transplant",
      name: "Liver Transplant",
      slug: "liver-transplant",
      department: "Gastroenterology",
      description: "A surgical procedure to replace a diseased liver with a healthy liver from a donor.",
      duration_minutes: 480,
      tags: ["transplant", "liver", "surgery"],
      starting_price: 1500000,
      price_range: { min: 1500000, max: 3000000 },
      branches_available: ["branch_apollo_delhi", "branch_apollo_chennai", "branch_fortis_fmri"],
      related_doctors: ["dr_subhash_gupta", "dr_anupam_singh", "dr_subhash_agarwal"],
      faqs: [],
      attachments: [],
    },
    {
      id: "treat_cancer_therapy",
      name: "Oncology Treatment",
      slug: "cancer-treatment",
      department: "Oncology",
      description: "A comprehensive range of treatments including chemotherapy, radiation therapy, and surgical oncology to treat various types of cancer.",
      duration_minutes: null,
      tags: ["oncology", "cancer", "chemotherapy"],
      starting_price: 20000,
      price_range: { min: 20000, max: 2000000 },
      branches_available: ["branch_max_saket", "branch_max_shalimar_bagh", "branch_apollo_delhi", "branch_fortis_fmri"],
      related_doctors: ["dr_harit_chaturvedi", "dr_rahul_bhargava"],
      faqs: [],
      attachments: [],
    },
  ],
  attachments: [],
};